FROM node:alpine AS build

WORKDIR /build-applicant

COPY /build-applicant/package*.json .

RUN npm config set registry https://registry.npmjs.org/
RUN npm install -g npm@latest


RUN npm install --legacy-peer-deps

COPY /build-applicant .

RUN npm run build

FROM nginx


COPY --from=build /build-applicant/build /usr/share/nginx/html


# Nginx configuration (if needed)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
