version: '3.8'
services:
    db:
        container_name: db-recruitment-mariadb
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
            - "3306"
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: recruitment-sumitomo-test
            MYSQL_USER: root
            MYSQL_PASSWORD: admin
        ports:
            - "9911:3306"
    app:
        container_name: app-recruitment-api
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
        ports:
            - "8000:8000"
    app-applicant:
        build:
            context: .
            dockerfile: Dockerfile.applicant.dev
        ports:
            - "3000:3000"
        volumes:
            - ./build-applicant:/build-applicant
            - node_modules:/build-applicant/node_modules/
volumes:
    node_modules:
    # app-admin:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.admin
    #     ports:
    #         - "8082:80"
