FROM node:latest AS builder

WORKDIR /usr/src/app

COPY build-admin/package*.json ./

RUN npm install --legacy-peer-deps

COPY build-admin/ .

RUN npm run build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /usr/src/app/build .

EXPOSE 80

# Nginx configuration (if needed)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
